version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: 'postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: 'polaris'
        POSTGRES_USER: 'postgres'
    network_mode: host
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data/

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:latest
    pull_policy: always
    restart: always
    container_name: 'smart-contract-verifier'
    network_mode: host

  blockscout:
    depends_on:
      - db
      - smart-contract-verifier
    image: gitea.qianking.xyz:3443/clayyu/chainexploer:latest
    restart: always
    stop_grace_period: 5m
    container_name: 'blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    network_mode: host
    environment:
      - MIX_ENV=prod
      - ETHEREUM_JSONRPC_VARIANT=geth
      - CHAIN_ID=12345
      - ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
      - ETHEREUM_JSONRPC_TRACE_URL=http://localhost:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://localhost:8546
      - SECRET_KEY_BASE="l4Z2o45D9Cvz7lezp30vxu4mCXqeKzXozjJjioYzWBlXM/NHEAu9/2OyWTIM0+1Y"
      - SUBNETWORK="Orbites"
      - COIN="ORB"
      - COIN_NAME="ORB"
      - DATABASE_URL=postgresql://postgres:polaris@localhost:5432/blockscout
      - ECTO_USE_SSL="false"
      - BLOCKSCOUT_PROTOCOL="http"
      - PORT=4000
      - DISABLE_EXCHANGE_RATES="true"
      - POOL_SIZE=40
      - POOL_SIZE_API=40
      - ACCOUNT_POOL_SIZE=10
      - HEART_BEAT_TIMEOUT=600
      - INDEXER_MEMORY_LIMIT="10GB"
      - FETCH_REWARDS_WAY="manual"
      - MICROSERVICE_SC_VERIFIER_ENABLED=true
      - MICROSERVICE_SC_VERIFIER_URL=http://localhost:8050
    volumes:
      - ./logs/:/app/logs/