      - MIX_ENV=prod
      - ETHEREUM_JSONRPC_VARIANT=geth
      - CHAIN_ID=12345
      - ETHEREUM_JSONRPC_HTTP_URL=http://172.21.87.231:8545
      - ETHEREUM_JSONRPC_TRACE_URL=http://172.21.87.231:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://172.21.87.231:8546
        #- FIRST_BLOCK=?xx
        #- TRACE_FIRST_BLOCK=?xx
      - SECRET_KEY_BASE="l4Z2o45D9Cvz7lezp30vxu4mCXqeKzXozjJjioYzWBlXM/NHEAu9/2OyWTIM0+1Y"
      - SUBNETWORK=Orbites
      - COIN=ORB
      - COIN_NAME=ORB
      - DATABASE_URL=postgresql://postgres:polaris@host.docker.internal:5432/blockscout
      - ECTO_USE_SSL=false
      - BLOCKSCOUT_PROTOCOL="http"
      - PORT=4000
      - INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true
      - HIDE_BLOCK_MINER=true
        #  - INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true #disable internal tx debug
        #- ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true # disable getBalance from before blocks
      # - DISABLE_EXCHANGE_RATES=true
      - POOL_SIZE=50
      - POOL_SIZE_API=50
      - ACCOUNT_POOL_SIZE=10
      - HEART_BEAT_TIMEOUT=600
      - INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE=500
      - INDEXER_MEMORY_LIMIT="10GB"
      - FETCH_REWARDS_WAY="manual"
      - MICROSERVICE_SC_VERIFIER_ENABLED=true
      - MICROSERVICE_SC_VERIFIER_URL=http://host.docker.internal:8050
