version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: 'postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: 'polaris'
        POSTGRES_USER: 'postgres'
    ports:
      - 5432:5432
    # network_mode: host
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data/

  smart-contract-verifier:
    image: yuhuajing/smart-contract-verifier:latest
    restart: always
    container_name: 'smart-contract-verifier'
    ports:
      - 8050:8050
    # network_mode: host
    environment:
      - SMART_CONTRACT_VERIFIER__SOLIDITY__ENABLED=true
      - SMART_CONTRACT_VERIFIER__VYPER__ENABLED=false
      - SMART_CONTRACT_VERIFIER__SOURCIFY__ENABLED=false
      - SMART_CONTRACT_VERIFIER__METRICS__ENABLED=false    

  blockscout:
    depends_on:
      - db
      - smart-contract-verifier
    image: blockscout/blockscout:latest
    stop_grace_period: 5m
    container_name: 'blockscout'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    #network_mode: host
    environment:
      - DATABASE_URL=postgresql://postgres:polaris@host.docker.internal:5432/blockscout
      - ECTO_USE_SSL=false
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal8545
      - ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://host.docker.internal:8546
      - MIX_ENV=prod
      - SECRET_KEY_BASE="l4Z2o45D9Cvz7lezp30vxu4mCXqeKzXozjJjioYzWBlXM/NHEAu9/2OyWTIM0+1Y"
      - CHAIN_ID=12345
      - SUBNETWORK=Orbites
      - COIN_NAME=ORB
      - INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true
      - INDEXER_DISABLE_EMPTY_BLOCKS_SANITIZER=true
      - INDEXER_DISABLE_TOKEN_INSTANCE_RETRY_FETCHER=true
      - HIDE_BLOCK_MINER=true
      - MICROSERVICE_SC_VERIFIER_ENABLED=true
      - MICROSERVICE_SC_VERIFIER_URL=http://host.docker.internal:8050
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/
