version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: 'postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: 'polaris'
        POSTGRES_USER: 'postgres'
    network_mode: host
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data/

  smart-contract-verifier:
    image: yuhuajing/smart-contract-verifier:latest
    restart: always
    container_name: 'smart-contract-verifier'
    network_mode: host

  blockscout:
    depends_on:
      - db
      - smart-contract-verifier
    image: blockscout/blockscout:latest
    #restart: always
    stop_grace_period: 5m
    container_name: 'blockscout'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    network_mode: host
    environment:
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
      - ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:8546
      - DATABASE_URL=postgresql://postgres:polaris@127.0.0.1:5432/blockscout
      - ECTO_USE_SSL="false"
      - MIX_ENV=prod
      - SECRET_KEY_BASE="l4Z2o45D9Cvz7lezp30vxu4mCXqeKzXozjJjioYzWBlXM/NHEAu9/2OyWTIM0+1Y"
      - CHAIN_ID=12345
      - SUBNETWORK=Orbites
      - COIN_NAME=ORB
      - INDEXER_DISABLE_BLOCK_REWARD_FETCHER=true
      - INDEXER_DISABLE_EMPTY_BLOCKS_SANITIZER=true
      - INDEXER_DISABLE_TOKEN_INSTANCE_RETRY_FETCHER=true
      - HIDE_BLOCK_MINER=true
      - MICROSERVICE_SC_VERIFIER_ENABLED=true
      - MICROSERVICE_SC_VERIFIER_URL=http://127.0.0.1:8050
      
    volumes:
      - ./logs/:/app/logs/
