version: '3.4'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD="polaris"
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    # ports:
    #   - "5432:5432"
    networks:
      - localnet

  smartcontractverifier:
    image: ghcr.io/blockscout/smart-contract-verifier
    container_name: smart-contract-verifier
    # ports:
    #   - "8050:8050"
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
