version: '3.8'

services:
  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:latest
    pull_policy: always
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  ../envs/common-smart-contract-verifier.env
    ports:
      - 8050:8050
