version: '3.8'

services:
  visualizer:
    image: ghcr.io/blockscout/visualizer:latest
    pull_policy: always
    restart: always
    container_name: 'visualizer'
    env_file:
      -  ../envs/common-visualizer.env
    ports:
      - 8152:8050
